-- Add missing content keys for CMS internationalization
INSERT INTO public.content_translations (content_key, content_type, page, section, english_text, description) VALUES
-- Shop Page
('shop.hero.title', 'heading', 'shop', 'hero', 'Browse Our Products', 'Main hero title for shop page'),
('shop.hero.subtitle', 'text', 'shop', 'hero', 'Discover custom 3D printed car parts, home decor, and unique designs', 'Hero subtitle for shop page'),
('shop.search.placeholder', 'placeholder', 'shop', 'search', 'Search products...', 'Search input placeholder'),
('shop.category.all', 'text', 'shop', 'category', 'All', 'All products category filter'),
('shop.category.car_parts', 'text', 'shop', 'category', 'Car Parts', 'Car parts category filter'),
('shop.category.home_decor', 'text', 'shop', 'category', 'Home Decor', 'Home decor category filter'),
('shop.category.custom', 'text', 'shop', 'category', 'Custom Designs', 'Custom designs category filter'),
('shop.no_products', 'text', 'shop', 'content', 'No products found', 'Message when no products match search'),

-- FAQ Page
('faq.hero.title', 'heading', 'faq', 'hero', 'How Can We Help You?', 'Main hero title for FAQ page'),
('faq.hero.subtitle', 'text', 'faq', 'hero', 'Find answers to common questions about our 3D model generation service', 'Hero subtitle for FAQ page'),
('faq.section.title', 'heading', 'faq', 'content', 'Frequently Asked Questions', 'FAQ section title'),
('faq.section.description', 'text', 'faq', 'content', 'Everything you need to know about our service', 'FAQ section description'),
('faq.q1.question', 'heading', 'faq', 'questions', 'What file formats do you provide?', 'Question 1'),
('faq.q1.answer', 'text', 'faq', 'answers', 'We generate both STL and BLEND files for all 3D models. STL files are ready for 3D printing, while BLEND files can be edited in Blender.', 'Answer 1'),
('faq.q2.question', 'heading', 'faq', 'questions', 'How long does it take to generate a model?', 'Question 2'),
('faq.q2.answer', 'text', 'faq', 'answers', 'Most models are generated within 2-5 minutes. Complex designs may take up to 10 minutes. You''ll receive a notification when your model is ready.', 'Answer 2'),
('faq.q3.question', 'heading', 'faq', 'questions', 'Can I customize the dimensions?', 'Question 3'),
('faq.q3.answer', 'text', 'faq', 'answers', 'Yes! You can specify custom width, height, and depth dimensions when creating your model. We also offer predefined sizes for common use cases.', 'Answer 3'),
('faq.q4.question', 'heading', 'faq', 'questions', 'What payment methods do you accept?', 'Question 4'),
('faq.q4.answer', 'text', 'faq', 'answers', 'We accept MB Way, PayPal, and major credit cards. All payments are processed securely.', 'Answer 4'),
('faq.q5.question', 'heading', 'faq', 'questions', 'Can I request revisions to my model?', 'Question 5'),
('faq.q5.answer', 'text', 'faq', 'answers', 'Yes! After receiving your initial model, you can request modifications. Additional charges may apply for major redesigns.', 'Answer 5'),
('faq.q6.question', 'heading', 'faq', 'questions', 'What materials can I choose from?', 'Question 6'),
('faq.q6.answer', 'text', 'faq', 'answers', 'We optimize models for PLA, ABS, PETG, Resin, and TPU materials. Each material has different properties suitable for various applications.', 'Answer 6'),
('faq.q7.question', 'heading', 'faq', 'questions', 'Do you offer refunds?', 'Question 7'),
('faq.q7.answer', 'text', 'faq', 'answers', 'We offer refunds within 7 days if you''re not satisfied with your model and haven''t downloaded the files yet. Please contact support for assistance.', 'Answer 7'),
('faq.q8.question', 'heading', 'faq', 'questions', 'How do I use the generated files?', 'Question 8'),
('faq.q8.answer', 'text', 'faq', 'answers', 'Download the STL file and import it into your preferred slicing software (like Cura or PrusaSlicer) to prepare it for printing. BLEND files can be edited in Blender.', 'Answer 8'),

-- Contact Page
('contact.hero.title', 'heading', 'contact', 'hero', 'Let''s Connect', 'Main hero title for contact page'),
('contact.hero.subtitle', 'text', 'contact', 'hero', 'Have a question or need support? We''re here to help you create amazing 3D models', 'Hero subtitle for contact page'),
('contact.info.email.title', 'heading', 'contact', 'info', 'Email', 'Email contact info title'),
('contact.info.email.value', 'text', 'contact', 'info', 'support@pompousweek.com', 'Email contact value'),
('contact.info.chat.title', 'heading', 'contact', 'info', 'Live Chat', 'Live chat contact info title'),
('contact.info.chat.value', 'text', 'contact', 'info', 'Available 9AM - 6PM GMT', 'Live chat contact value'),
('contact.info.response.title', 'heading', 'contact', 'info', 'Response Time', 'Response time contact info title'),
('contact.info.response.value', 'text', 'contact', 'info', 'Within 24/48 hours', 'Response time contact value'),
('contact.form.title', 'heading', 'contact', 'form', 'Send Us a Message', 'Contact form title'),
('contact.form.description', 'text', 'contact', 'form', 'Fill out the form below and we''ll get back to you as soon as possible', 'Contact form description'),
('contact.form.name', 'label', 'contact', 'form', 'Name', 'Name field label'),
('contact.form.name.placeholder', 'placeholder', 'contact', 'form', 'Your name', 'Name field placeholder'),
('contact.form.email', 'label', 'contact', 'form', 'Email', 'Email field label'),
('contact.form.email.placeholder', 'placeholder', 'contact', 'form', 'your@email.com', 'Email field placeholder'),
('contact.form.subject', 'label', 'contact', 'form', 'Subject', 'Subject field label'),
('contact.form.subject.placeholder', 'placeholder', 'contact', 'form', 'What is this about?', 'Subject field placeholder'),
('contact.form.message', 'label', 'contact', 'form', 'Message', 'Message field label'),
('contact.form.message.placeholder', 'placeholder', 'contact', 'form', 'Tell us more about your inquiry...', 'Message field placeholder'),
('contact.form.send', 'button', 'contact', 'form', 'Send Message', 'Send message button'),
('contact.form.sending', 'text', 'contact', 'form', 'Sending...', 'Sending state text'),
('contact.form.success', 'text', 'contact', 'form', 'Message sent successfully! We''ll get back to you soon.', 'Success message'),

-- About Page
('about.hero.title', 'heading', 'about', 'hero', 'Empowering Creators', 'Main hero title for about page'),
('about.hero.subtitle', 'text', 'about', 'hero', 'We''re on a mission to democratize 3D design and make custom manufacturing accessible to everyone', 'Hero subtitle for about page'),
('about.story.title', 'heading', 'about', 'story', 'Our Story', 'Story section title'),
('about.story.subtitle', 'text', 'about', 'story', 'How it all began', 'Story section subtitle'),
('about.story.paragraph1', 'text', 'about', 'story', 'Founded in 2021, Pompousweek started with a simple idea around Quality Assurance. Then we decided to grow as company and had this idea: what if anyone could create professional-quality 3D models without years of CAD training? We saw the rise of 3D printing and AI technology converging, creating a unique opportunity to bridge the gap between imagination and reality.', 'Story paragraph 1'),
('about.story.paragraph2', 'text', 'about', 'story', 'Our team of engineers, designers, and AI specialists came together to build a platform that understands your needs and translates them into print-ready 3D models. Whether you''re a hobbyist looking to create custom car parts or a designer crafting unique home decorations, we''re here to help you bring your ideas to life.', 'Story paragraph 2'),
('about.story.paragraph3', 'text', 'about', 'story', 'Today, we''re proud to serve a growing community of makers, DIY enthusiasts, and professional designers who use our platform to create everything from functional prototypes to artistic masterpieces.', 'Story paragraph 3'),
('about.values.heading', 'heading', 'about', 'values', 'Our Values', 'Values section heading'),
('about.values.subtitle', 'text', 'about', 'values', 'What drives us every day', 'Values section subtitle'),
('about.values.innovation.title', 'heading', 'about', 'values', 'Innovation', 'Innovation value title'),
('about.values.innovation.description', 'text', 'about', 'values', 'Leveraging cutting-edge AI technology to make 3D modeling accessible to everyone', 'Innovation value description'),
('about.values.quality.title', 'heading', 'about', 'values', 'Quality', 'Quality value title'),
('about.values.quality.description', 'text', 'about', 'values', 'Delivering high-quality, print-ready models that meet professional standards', 'Quality value description'),
('about.values.community.title', 'heading', 'about', 'values', 'Community', 'Community value title'),
('about.values.community.description', 'text', 'about', 'values', 'Building a community of makers, designers, and 3D printing enthusiasts', 'Community value description'),
('about.values.passion.title', 'heading', 'about', 'values', 'Passion', 'Passion value title'),
('about.values.passion.description', 'text', 'about', 'values', 'Driven by our love for innovation, design, and helping others create', 'Passion value description'),

-- Generator Page
('generator.form.title', 'heading', 'generator', 'form', 'Create Your 3D Model', 'Generator form title'),
('generator.form.subtitle', 'text', 'generator', 'form', 'Describe your vision and let our AI bring it to life', 'Generator form subtitle'),

-- Cart Page
('cart.title', 'heading', 'cart', 'header', 'Shopping Cart', 'Cart page title'),
('cart.subtitle', 'text', 'cart', 'header', 'Your Items', 'Cart page subtitle'),
('cart.empty.title', 'heading', 'cart', 'empty', 'Your Cart is Empty', 'Empty cart title'),
('cart.empty.description', 'text', 'cart', 'empty', 'Add some products to get started', 'Empty cart description'),
('cart.empty.button', 'button', 'cart', 'empty', 'Browse Products', 'Empty cart browse button'),
('cart.items_count', 'text', 'cart', 'header', 'items', 'Items count suffix'),
('cart.summary.title', 'heading', 'cart', 'summary', 'Order Summary', 'Order summary title'),
('cart.summary.subtotal', 'text', 'cart', 'summary', 'Subtotal', 'Subtotal label'),
('cart.summary.shipping', 'text', 'cart', 'summary', 'Shipping', 'Shipping label'),
('cart.summary.shipping_calculated', 'text', 'cart', 'summary', 'Calculated at checkout', 'Shipping calculated text'),
('cart.summary.total', 'text', 'cart', 'summary', 'Total', 'Total label'),
('cart.checkout_button', 'button', 'cart', 'summary', 'Proceed to Checkout', 'Checkout button'),

-- Wishlist Page
('wishlist.title', 'heading', 'wishlist', 'header', 'My Wishlist', 'Wishlist page title'),
('wishlist.subtitle', 'text', 'wishlist', 'header', 'Your Saved Items', 'Wishlist page subtitle'),
('wishlist.tabs.products', 'text', 'wishlist', 'tabs', 'Products', 'Products tab'),
('wishlist.tabs.designs', 'text', 'wishlist', 'tabs', 'Designs', 'Designs tab'),
('wishlist.products.empty', 'text', 'wishlist', 'products', 'No products in your wishlist yet', 'Empty products message'),
('wishlist.products.browse', 'button', 'wishlist', 'products', 'Browse Products', 'Browse products button'),
('wishlist.designs.empty', 'text', 'wishlist', 'designs', 'No designs in your wishlist yet', 'Empty designs message'),
('wishlist.designs.generate', 'button', 'wishlist', 'designs', 'Generate Designs', 'Generate designs button'),
('wishlist.add_to_cart', 'button', 'wishlist', 'products', 'Add to Cart', 'Add to cart button'),
('wishlist.out_of_stock', 'text', 'wishlist', 'products', 'Out of stock', 'Out of stock text'),
('wishlist.download_stl', 'button', 'wishlist', 'designs', 'Download STL', 'Download STL button'),
('wishlist.created', 'text', 'wishlist', 'designs', 'Created', 'Created label'),

-- Auth Page
('auth.title', 'heading', 'auth', 'header', '3D Model Generator', 'Auth page title'),
('auth.login.subtitle', 'text', 'auth', 'form', 'Welcome back! Please login to continue.', 'Login subtitle'),
('auth.signup.subtitle', 'text', 'auth', 'form', 'Create an account to start generating 3D models.', 'Signup subtitle'),
('auth.email', 'label', 'auth', 'form', 'Email', 'Email field label'),
('auth.email.placeholder', 'placeholder', 'auth', 'form', 'you@example.com', 'Email placeholder'),
('auth.password', 'label', 'auth', 'form', 'Password', 'Password field label'),
('auth.password.placeholder', 'placeholder', 'auth', 'form', '••••••••', 'Password placeholder'),
('auth.login.button', 'button', 'auth', 'form', 'Login', 'Login button'),
('auth.signup.button', 'button', 'auth', 'form', 'Sign Up', 'Signup button'),
('auth.login.loading', 'text', 'auth', 'form', 'Logging in...', 'Login loading text'),
('auth.signup.loading', 'text', 'auth', 'form', 'Creating account...', 'Signup loading text'),
('auth.switch.to_signup', 'text', 'auth', 'form', 'Need an account? Sign up', 'Switch to signup link'),
('auth.switch.to_login', 'text', 'auth', 'form', 'Already have an account? Login', 'Switch to login link'),

-- Checkout Page
('checkout.title', 'heading', 'checkout', 'header', 'Checkout', 'Checkout page title'),
('checkout.subtitle', 'text', 'checkout', 'header', 'Complete Your Purchase', 'Checkout page subtitle'),
('checkout.summary.title', 'heading', 'checkout', 'summary', 'Order Summary', 'Order summary title'),
('checkout.summary.description', 'text', 'checkout', 'summary', '3D Model Generation', 'Order summary description'),
('checkout.summary.total', 'text', 'checkout', 'summary', 'Total', 'Total label'),
('checkout.payment.title', 'heading', 'checkout', 'payment', 'Payment Method', 'Payment method title'),
('checkout.payment.subtitle', 'text', 'checkout', 'payment', 'Secure payment powered by Stripe', 'Payment subtitle'),
('checkout.payment.methods.title', 'heading', 'checkout', 'payment', 'Accepted Payment Methods', 'Payment methods title'),
('checkout.payment.methods.cards', 'text', 'checkout', 'payment', '• Credit & Debit Cards (Visa, Mastercard, Amex)', 'Cards payment method'),
('checkout.payment.methods.paypal', 'text', 'checkout', 'payment', '• PayPal', 'PayPal payment method'),
('checkout.payment.methods.multibanco', 'text', 'checkout', 'payment', '• Multibanco (Portugal)', 'Multibanco payment method'),
('checkout.payment.methods.mbway', 'text', 'checkout', 'payment', '• MB WAY available through Multibanco', 'MB WAY payment method'),
('checkout.payment.button', 'button', 'checkout', 'payment', 'Pay €9.99 with Stripe', 'Payment button'),
('checkout.payment.processing', 'text', 'checkout', 'payment', 'Redirecting to Stripe...', 'Processing text'),
('checkout.security.stripe', 'text', 'checkout', 'security', '🔒 Your payment is secured by Stripe', 'Stripe security text'),
('checkout.security.methods', 'text', 'checkout', 'security', '💳 All major payment methods accepted', 'Payment methods security text'),
('checkout.security.portuguese', 'text', 'checkout', 'security', '🇵🇹 Portuguese payment methods supported', 'Portuguese methods security text'),
('checkout.terms', 'text', 'checkout', 'terms', 'By completing this purchase, you agree to our Terms of Service', 'Terms agreement text'),

-- User Dashboard Page
('dashboard.title', 'heading', 'dashboard', 'header', 'My Dashboard', 'Dashboard page title'),
('dashboard.subtitle', 'text', 'dashboard', 'header', 'Manage your account', 'Dashboard page subtitle'),
('dashboard.back_home', 'button', 'dashboard', 'header', 'Back to Home', 'Back to home button'),
('dashboard.tabs.designs', 'text', 'dashboard', 'tabs', 'My Designs', 'Designs tab'),
('dashboard.tabs.orders', 'text', 'dashboard', 'tabs', 'Order History', 'Orders tab'),
('dashboard.tabs.profile', 'text', 'dashboard', 'tabs', 'Personal Info', 'Profile tab'),
('dashboard.tabs.billing', 'text', 'dashboard', 'tabs', 'Billing & Address', 'Billing tab'),
('dashboard.orders.title', 'heading', 'dashboard', 'orders', 'Payment History', 'Orders section title'),
('dashboard.orders.description', 'text', 'dashboard', 'orders', 'View all your past transactions', 'Orders section description'),
('dashboard.orders.empty', 'text', 'dashboard', 'orders', 'No payments yet', 'Empty orders message'),
('dashboard.profile.title', 'heading', 'dashboard', 'profile', 'Personal Information', 'Profile section title'),
('dashboard.profile.description', 'text', 'dashboard', 'profile', 'Update your personal details', 'Profile section description'),
('dashboard.profile.email', 'label', 'dashboard', 'profile', 'Email', 'Email field label'),
('dashboard.profile.first_name', 'label', 'dashboard', 'profile', 'First Name', 'First name field label'),
('dashboard.profile.first_name.required', 'text', 'dashboard', 'profile', 'Required for shipping', 'First name required text'),
('dashboard.profile.last_name', 'label', 'dashboard', 'profile', 'Last Name', 'Last name field label'),
('dashboard.profile.last_name.required', 'text', 'dashboard', 'profile', 'Required for shipping', 'Last name required text'),
('dashboard.profile.phone', 'label', 'dashboard', 'profile', 'Phone Number', 'Phone field label'),
('dashboard.profile.phone.help', 'text', 'dashboard', 'profile', 'Required for order updates. Use international format (e.g., +1234567890)', 'Phone help text'),
('dashboard.profile.save', 'button', 'dashboard', 'profile', 'Save Changes', 'Save profile button'),
('dashboard.billing.title', 'heading', 'dashboard', 'billing', 'Billing & Address Information', 'Billing section title'),
('dashboard.billing.description', 'text', 'dashboard', 'billing', 'Manage your invoicing details', 'Billing section description'),
('dashboard.billing.company', 'label', 'dashboard', 'billing', 'Company Name (Optional)', 'Company field label'),
('dashboard.billing.vat', 'label', 'dashboard', 'billing', 'VAT Number (Optional)', 'VAT field label'),
('dashboard.billing.address', 'label', 'dashboard', 'billing', 'Street Address', 'Address field label'),
('dashboard.billing.address.required', 'text', 'dashboard', 'billing', 'Required for product shipping', 'Address required text'),
('dashboard.billing.city', 'label', 'dashboard', 'billing', 'City', 'City field label'),
('dashboard.billing.postal_code', 'label', 'dashboard', 'billing', 'Postal Code', 'Postal code field label'),
('dashboard.billing.country', 'label', 'dashboard', 'billing', 'Country', 'Country field label'),
('dashboard.billing.country.help', 'text', 'dashboard', 'billing', 'Use 2-letter code (e.g., GB, US, DE)', 'Country help text'),
('dashboard.billing.save', 'button', 'dashboard', 'billing', 'Save Billing Info', 'Save billing button'),

-- Footer Additional Content Keys
('footer.brand.description', 'text', 'footer', 'brand', 'Custom 3D printed solutions for car enthusiasts and home decorators. Quality, precision, and innovation in every design.', 'Footer brand description'),
('footer.products.title', 'heading', 'footer', 'products', 'Products', 'Footer products section title'),
('footer.products.all', 'text', 'footer', 'products', 'All Products', 'Footer all products link'),
('footer.products.models', 'text', 'footer', 'products', '3D Models', 'Footer 3D models link'),
('footer.products.car_parts', 'text', 'footer', 'products', 'Car Parts', 'Footer car parts link'),
('footer.products.home_decor', 'text', 'footer', 'products', 'Home Decor', 'Footer home decor link'),
('footer.services.title', 'heading', 'footer', 'services', 'Services', 'Footer services section title'),
('footer.services.ai_generator', 'text', 'footer', 'services', 'AI Model Generator', 'Footer AI generator link'),
('footer.services.custom_printing', 'text', 'footer', 'services', 'Custom Printing', 'Footer custom printing link'),
('footer.services.restoration', 'text', 'footer', 'services', 'Restoration Services', 'Footer restoration link'),
('footer.services.consultation', 'text', 'footer', 'services', 'Design Consultation', 'Footer consultation link'),
('footer.company.title', 'heading', 'footer', 'company', 'Company', 'Footer company section title'),
('footer.company.about', 'text', 'footer', 'company', 'About Us', 'Footer about link'),
('footer.company.contact', 'text', 'footer', 'company', 'Contact', 'Footer contact link'),
('footer.company.faq', 'text', 'footer', 'company', 'FAQ', 'Footer FAQ link'),
('footer.company.terms', 'text', 'footer', 'company', 'Terms of Service', 'Footer terms link');