-- Insert calculator translations for EN and PT-PT
INSERT INTO content_translations (content_key, page, section, content_type, english_text, portuguese_text) VALUES
-- CalculatorLayout
('calculator.nav.title', 'calculator', 'nav', 'text', 'Price Calculator', 'Calculadora de Preços'),
('calculator.nav.dashboard', 'calculator', 'nav', 'text', 'Dashboard', 'Painel'),
('calculator.nav.prints', 'calculator', 'nav', 'text', 'Prints', 'Impressões'),
('calculator.nav.printers', 'calculator', 'nav', 'text', 'Printers', 'Impressoras'),
('calculator.nav.filaments', 'calculator', 'nav', 'text', 'Filaments', 'Filamentos'),
('calculator.nav.settings', 'calculator', 'nav', 'text', 'Settings', 'Definições'),

-- CalcDashboard
('calculator.dashboard.pageTitle', 'calculator', 'dashboard', 'text', 'Price Calculator', 'Calculadora de Preços'),
('calculator.dashboard.pageSubtitle', 'calculator', 'dashboard', 'text', 'Calculate your 3D printing costs', 'Calcule os custos de impressão 3D'),
('calculator.dashboard.signInRequired', 'calculator', 'dashboard', 'text', 'Sign In Required', 'Iniciar Sessão Necessário'),
('calculator.dashboard.signInMessage', 'calculator', 'dashboard', 'text', 'Please sign in to access the Price Calculator', 'Por favor, inicie sessão para aceder à Calculadora de Preços'),
('calculator.dashboard.signIn', 'calculator', 'dashboard', 'text', 'Sign In', 'Iniciar Sessão'),
('calculator.dashboard.completeSetup', 'calculator', 'dashboard', 'text', 'Complete Your Setup', 'Complete a Configuração'),
('calculator.dashboard.setupMessage', 'calculator', 'dashboard', 'text', 'To start calculating print costs, you need to add a printer, filament, and electricity settings.', 'Para começar a calcular custos de impressão, precisa de adicionar uma impressora, filamento e configurações de eletricidade.'),
('calculator.dashboard.printerAdded', 'calculator', 'dashboard', 'text', 'Printer added', 'Impressora adicionada'),
('calculator.dashboard.addPrinter', 'calculator', 'dashboard', 'text', 'Add printer', 'Adicionar impressora'),
('calculator.dashboard.filamentAdded', 'calculator', 'dashboard', 'text', 'Filament added', 'Filamento adicionado'),
('calculator.dashboard.addFilament', 'calculator', 'dashboard', 'text', 'Add filament', 'Adicionar filamento'),
('calculator.dashboard.electricityConfigured', 'calculator', 'dashboard', 'text', 'Electricity configured', 'Eletricidade configurada'),
('calculator.dashboard.setElectricity', 'calculator', 'dashboard', 'text', 'Set electricity', 'Configurar eletricidade'),
('calculator.dashboard.startSetupWizard', 'calculator', 'dashboard', 'text', 'Start Setup Wizard', 'Iniciar Assistente de Configuração'),
('calculator.dashboard.printers', 'calculator', 'dashboard', 'text', 'Printers', 'Impressoras'),
('calculator.dashboard.filaments', 'calculator', 'dashboard', 'text', 'Filaments', 'Filamentos'),
('calculator.dashboard.calculations', 'calculator', 'dashboard', 'text', 'Calculations', 'Cálculos'),
('calculator.dashboard.totalProfit', 'calculator', 'dashboard', 'text', 'Total Profit', 'Lucro Total'),
('calculator.dashboard.quickActions', 'calculator', 'dashboard', 'text', 'Quick Actions', 'Ações Rápidas'),
('calculator.dashboard.newCalculation', 'calculator', 'dashboard', 'text', 'New Calculation', 'Novo Cálculo'),
('calculator.dashboard.managePrinters', 'calculator', 'dashboard', 'text', 'Manage Printers', 'Gerir Impressoras'),
('calculator.dashboard.manageFilaments', 'calculator', 'dashboard', 'text', 'Manage Filaments', 'Gerir Filamentos'),
('calculator.dashboard.recentCalculations', 'calculator', 'dashboard', 'text', 'Recent Calculations', 'Cálculos Recentes'),
('calculator.dashboard.viewAll', 'calculator', 'dashboard', 'text', 'View All', 'Ver Todos'),
('calculator.dashboard.cost', 'calculator', 'dashboard', 'text', 'Cost', 'Custo'),
('calculator.dashboard.margin', 'calculator', 'dashboard', 'text', 'margin', 'margem'),

-- CalcPrints
('calculator.prints.title', 'calculator', 'prints', 'text', 'Print Calculations', 'Cálculos de Impressão'),
('calculator.prints.subtitle', 'calculator', 'prints', 'text', 'Calculate costs and profits for your 3D prints', 'Calcule custos e lucros das suas impressões 3D'),
('calculator.prints.newCalculation', 'calculator', 'prints', 'text', 'New Calculation', 'Novo Cálculo'),
('calculator.prints.missingDataWarning', 'calculator', 'prints', 'text', 'Before creating print calculations, you need to add at least one', 'Antes de criar cálculos de impressão, precisa de adicionar pelo menos'),
('calculator.prints.printer', 'calculator', 'prints', 'text', 'printer', 'impressora'),
('calculator.prints.filament', 'calculator', 'prints', 'text', 'filament', 'filamento'),
('calculator.prints.and', 'calculator', 'prints', 'text', 'and', 'e'),
('calculator.prints.addPrinter', 'calculator', 'prints', 'text', 'Add Printer', 'Adicionar Impressora'),
('calculator.prints.addFilament', 'calculator', 'prints', 'text', 'Add Filament', 'Adicionar Filamento'),
('calculator.prints.savedCalculations', 'calculator', 'prints', 'text', 'Saved Calculations', 'Cálculos Guardados'),
('calculator.prints.noCalculations', 'calculator', 'prints', 'text', 'No calculations yet', 'Ainda não há cálculos'),
('calculator.prints.createFirst', 'calculator', 'prints', 'text', 'Create your first print calculation to get started', 'Crie o seu primeiro cálculo de impressão para começar'),
('calculator.prints.createNew', 'calculator', 'prints', 'text', 'Create New', 'Criar Novo'),
('calculator.prints.printDetails', 'calculator', 'prints', 'text', 'Print Details', 'Detalhes da Impressão'),
('calculator.prints.selectPrint', 'calculator', 'prints', 'text', 'Select a print to view details', 'Selecione uma impressão para ver os detalhes'),
('calculator.prints.edit', 'calculator', 'prints', 'text', 'Edit', 'Editar'),
('calculator.prints.duplicate', 'calculator', 'prints', 'text', 'Duplicate', 'Duplicar'),
('calculator.prints.delete', 'calculator', 'prints', 'text', 'Delete', 'Eliminar'),
('calculator.prints.costBreakdown', 'calculator', 'prints', 'text', 'Cost Breakdown', 'Decomposição de Custos'),
('calculator.prints.filamentCost', 'calculator', 'prints', 'text', 'Filament', 'Filamento'),
('calculator.prints.electricityCost', 'calculator', 'prints', 'text', 'Electricity', 'Eletricidade'),
('calculator.prints.depreciation', 'calculator', 'prints', 'text', 'Depreciation', 'Depreciação'),
('calculator.prints.labor', 'calculator', 'prints', 'text', 'Labor', 'Mão de Obra'),
('calculator.prints.shipping', 'calculator', 'prints', 'text', 'Shipping', 'Envio'),
('calculator.prints.consumables', 'calculator', 'prints', 'text', 'Consumables', 'Consumíveis'),
('calculator.prints.fixedExpenses', 'calculator', 'prints', 'text', 'Fixed Expenses', 'Despesas Fixas'),
('calculator.prints.totalCost', 'calculator', 'prints', 'text', 'Total Cost', 'Custo Total'),
('calculator.prints.pricing', 'calculator', 'prints', 'text', 'Pricing', 'Preçário'),
('calculator.prints.markup', 'calculator', 'prints', 'text', 'Markup', 'Margem'),
('calculator.prints.sellPrice', 'calculator', 'prints', 'text', 'Sell Price', 'Preço de Venda'),
('calculator.prints.profit', 'calculator', 'prints', 'text', 'Profit', 'Lucro'),
('calculator.prints.profitMargin', 'calculator', 'prints', 'text', 'Profit Margin', 'Margem de Lucro'),

-- Print Dialog
('calculator.prints.dialog.newTitle', 'calculator', 'prints', 'text', 'New Print Calculation', 'Novo Cálculo de Impressão'),
('calculator.prints.dialog.editTitle', 'calculator', 'prints', 'text', 'Edit Print Calculation', 'Editar Cálculo de Impressão'),
('calculator.prints.dialog.basicInfo', 'calculator', 'prints', 'text', 'Basic Info', 'Informação Básica'),
('calculator.prints.dialog.filaments', 'calculator', 'prints', 'text', 'Filaments', 'Filamentos'),
('calculator.prints.dialog.costSettings', 'calculator', 'prints', 'text', 'Cost Settings', 'Definições de Custo'),
('calculator.prints.dialog.name', 'calculator', 'prints', 'text', 'Name', 'Nome'),
('calculator.prints.dialog.printTime', 'calculator', 'prints', 'text', 'Print Time (min)', 'Tempo de Impressão (min)'),
('calculator.prints.dialog.printer', 'calculator', 'prints', 'text', 'Printer', 'Impressora'),
('calculator.prints.dialog.electricity', 'calculator', 'prints', 'text', 'Electricity Settings', 'Configurações de Eletricidade'),
('calculator.prints.dialog.shipping', 'calculator', 'prints', 'text', 'Shipping Option', 'Opção de Envio'),
('calculator.prints.dialog.laborTime', 'calculator', 'prints', 'text', 'Labor Time (min)', 'Tempo de Mão de Obra (min)'),
('calculator.prints.dialog.quantity', 'calculator', 'prints', 'text', 'Quantity', 'Quantidade'),
('calculator.prints.dialog.wastage', 'calculator', 'prints', 'text', 'Wastage %', 'Desperdício %'),
('calculator.prints.dialog.failureRate', 'calculator', 'prints', 'text', 'Failure Rate %', 'Taxa de Falha %'),
('calculator.prints.dialog.modelCost', 'calculator', 'prints', 'text', 'Model Cost (€)', 'Custo do Modelo (€)'),
('calculator.prints.dialog.markupPercent', 'calculator', 'prints', 'text', 'Markup %', 'Margem %'),
('calculator.prints.dialog.notes', 'calculator', 'prints', 'text', 'Notes', 'Notas'),
('calculator.prints.dialog.save', 'calculator', 'prints', 'text', 'Save', 'Guardar'),
('calculator.prints.dialog.cancel', 'calculator', 'prints', 'text', 'Cancel', 'Cancelar'),
('calculator.prints.dialog.selectPrinter', 'calculator', 'prints', 'text', 'Select printer', 'Selecionar impressora'),
('calculator.prints.dialog.selectElectricity', 'calculator', 'prints', 'text', 'Select electricity settings', 'Selecionar configurações de eletricidade'),
('calculator.prints.dialog.selectShipping', 'calculator', 'prints', 'text', 'Select shipping (optional)', 'Selecionar envio (opcional)'),
('calculator.prints.dialog.noShipping', 'calculator', 'prints', 'text', 'No shipping', 'Sem envio'),

-- CalcPrinters
('calculator.printers.pageTitle', 'calculator', 'printers', 'text', 'Printers', 'Impressoras'),
('calculator.printers.pageSubtitle', 'calculator', 'printers', 'text', 'Manage your 3D printers', 'Gerir as suas impressoras 3D'),
('calculator.printers.signInRequired', 'calculator', 'printers', 'text', 'Sign In Required', 'Iniciar Sessão Necessário'),
('calculator.printers.signInMessage', 'calculator', 'printers', 'text', 'Please sign in to manage your printers', 'Por favor, inicie sessão para gerir as suas impressoras'),
('calculator.printers.signIn', 'calculator', 'printers', 'text', 'Sign In', 'Iniciar Sessão'),
('calculator.printers.yourPrinters', 'calculator', 'printers', 'text', 'Your Printers', 'As Suas Impressoras'),
('calculator.printers.addPrinter', 'calculator', 'printers', 'text', 'Add Printer', 'Adicionar Impressora'),
('calculator.printers.editPrinter', 'calculator', 'printers', 'text', 'Edit Printer', 'Editar Impressora'),
('calculator.printers.addNewPrinter', 'calculator', 'printers', 'text', 'Add New Printer', 'Adicionar Nova Impressora'),
('calculator.printers.noPrinters', 'calculator', 'printers', 'text', 'No printers yet', 'Ainda não há impressoras'),
('calculator.printers.addFirstMessage', 'calculator', 'printers', 'text', 'Add your first 3D printer to get started', 'Adicione a sua primeira impressora 3D para começar'),
('calculator.printers.brand', 'calculator', 'printers', 'text', 'Brand', 'Marca'),
('calculator.printers.model', 'calculator', 'printers', 'text', 'Model', 'Modelo'),
('calculator.printers.selectBrand', 'calculator', 'printers', 'text', 'Select brand', 'Selecionar marca'),
('calculator.printers.selectModel', 'calculator', 'printers', 'text', 'Select model', 'Selecionar modelo'),
('calculator.printers.printerName', 'calculator', 'printers', 'text', 'Printer Name', 'Nome da Impressora'),
('calculator.printers.purchaseCost', 'calculator', 'printers', 'text', 'Purchase Cost (€)', 'Custo de Compra (€)'),
('calculator.printers.power', 'calculator', 'printers', 'text', 'Power (Watts)', 'Potência (Watts)'),
('calculator.printers.depreciationMonths', 'calculator', 'printers', 'text', 'Depreciation (months)', 'Depreciação (meses)'),
('calculator.printers.depreciationHours', 'calculator', 'printers', 'text', 'Depreciation (hours)', 'Depreciação (horas)'),
('calculator.printers.maintenanceCost', 'calculator', 'printers', 'text', 'Maintenance Cost / Year (€)', 'Custo de Manutenção / Ano (€)'),
('calculator.printers.notes', 'calculator', 'printers', 'text', 'Notes', 'Notas'),
('calculator.printers.updatePrinter', 'calculator', 'printers', 'text', 'Update Printer', 'Atualizar Impressora'),
('calculator.printers.life', 'calculator', 'printers', 'text', 'life', 'vida útil'),

-- CalcFilaments
('calculator.filaments.pageTitle', 'calculator', 'filaments', 'text', 'Filaments', 'Filamentos'),
('calculator.filaments.pageSubtitle', 'calculator', 'filaments', 'text', 'Manage your filament inventory', 'Gerir o seu inventário de filamentos'),
('calculator.filaments.signInRequired', 'calculator', 'filaments', 'text', 'Sign In Required', 'Iniciar Sessão Necessário'),
('calculator.filaments.signInMessage', 'calculator', 'filaments', 'text', 'Please sign in to manage your filaments', 'Por favor, inicie sessão para gerir os seus filamentos'),
('calculator.filaments.signIn', 'calculator', 'filaments', 'text', 'Sign In', 'Iniciar Sessão'),
('calculator.filaments.yourFilaments', 'calculator', 'filaments', 'text', 'Your Filaments', 'Os Seus Filamentos'),
('calculator.filaments.addFilament', 'calculator', 'filaments', 'text', 'Add Filament', 'Adicionar Filamento'),
('calculator.filaments.editFilament', 'calculator', 'filaments', 'text', 'Edit Filament', 'Editar Filamento'),
('calculator.filaments.addNewFilament', 'calculator', 'filaments', 'text', 'Add New Filament', 'Adicionar Novo Filamento'),
('calculator.filaments.noFilaments', 'calculator', 'filaments', 'text', 'No filaments yet', 'Ainda não há filamentos'),
('calculator.filaments.addFirstMessage', 'calculator', 'filaments', 'text', 'Add your first filament to start calculating costs', 'Adicione o seu primeiro filamento para começar a calcular custos'),
('calculator.filaments.filamentName', 'calculator', 'filaments', 'text', 'Filament Name', 'Nome do Filamento'),
('calculator.filaments.brand', 'calculator', 'filaments', 'text', 'Brand', 'Marca'),
('calculator.filaments.material', 'calculator', 'filaments', 'text', 'Material', 'Material'),
('calculator.filaments.color', 'calculator', 'filaments', 'text', 'Color', 'Cor'),
('calculator.filaments.selectBrand', 'calculator', 'filaments', 'text', 'Select brand', 'Selecionar marca'),
('calculator.filaments.selectMaterial', 'calculator', 'filaments', 'text', 'Select material', 'Selecionar material'),
('calculator.filaments.selectColor', 'calculator', 'filaments', 'text', 'Select color', 'Selecionar cor'),
('calculator.filaments.spoolWeight', 'calculator', 'filaments', 'text', 'Spool Weight (g)', 'Peso do Rolo (g)'),
('calculator.filaments.spoolCost', 'calculator', 'filaments', 'text', 'Spool Cost (€)', 'Custo do Rolo (€)'),
('calculator.filaments.costPerGram', 'calculator', 'filaments', 'text', 'Cost per gram', 'Custo por grama'),
('calculator.filaments.density', 'calculator', 'filaments', 'text', 'Density (g/cm³)', 'Densidade (g/cm³)'),
('calculator.filaments.notes', 'calculator', 'filaments', 'text', 'Notes', 'Notas'),
('calculator.filaments.updateFilament', 'calculator', 'filaments', 'text', 'Update Filament', 'Atualizar Filamento'),

-- CalcSettings
('calculator.settings.pageTitle', 'calculator', 'settings', 'text', 'Settings', 'Definições'),
('calculator.settings.pageSubtitle', 'calculator', 'settings', 'text', 'Configure your calculator settings', 'Configure as definições da calculadora'),
('calculator.settings.signInRequired', 'calculator', 'settings', 'text', 'Sign In Required', 'Iniciar Sessão Necessário'),
('calculator.settings.signIn', 'calculator', 'settings', 'text', 'Sign In', 'Iniciar Sessão'),
('calculator.settings.save', 'calculator', 'settings', 'text', 'Save', 'Guardar'),
('calculator.settings.unsavedChanges', 'calculator', 'settings', 'text', 'Unsaved changes', 'Alterações não guardadas'),
('calculator.settings.electricity', 'calculator', 'settings', 'text', 'Electricity', 'Eletricidade'),
('calculator.settings.expenses', 'calculator', 'settings', 'text', 'Expenses', 'Despesas'),
('calculator.settings.consumables', 'calculator', 'settings', 'text', 'Consumables', 'Consumíveis'),
('calculator.settings.shipping', 'calculator', 'settings', 'text', 'Shipping', 'Envio'),
('calculator.settings.labor', 'calculator', 'settings', 'text', 'Labor', 'Mão de Obra'),
('calculator.settings.electricitySettings', 'calculator', 'settings', 'text', 'Electricity Settings', 'Configurações de Eletricidade'),
('calculator.settings.fixedExpenses', 'calculator', 'settings', 'text', 'Fixed Monthly Expenses', 'Despesas Mensais Fixas'),
('calculator.settings.consumablesPerPrint', 'calculator', 'settings', 'text', 'Consumables (per print)', 'Consumíveis (por impressão)'),
('calculator.settings.shippingOptions', 'calculator', 'settings', 'text', 'Shipping Options', 'Opções de Envio'),
('calculator.settings.laborSettings', 'calculator', 'settings', 'text', 'Labor Settings', 'Configurações de Mão de Obra'),
('calculator.settings.add', 'calculator', 'settings', 'text', 'Add', 'Adicionar'),
('calculator.settings.perKwh', 'calculator', 'settings', 'text', '€/kWh', '€/kWh'),
('calculator.settings.perMonth', 'calculator', 'settings', 'text', '€/month', '€/mês'),
('calculator.settings.perPrint', 'calculator', 'settings', 'text', '€/print', '€/impressão'),
('calculator.settings.noElectricity', 'calculator', 'settings', 'text', 'No electricity settings yet', 'Ainda não há configurações de eletricidade'),
('calculator.settings.noExpenses', 'calculator', 'settings', 'text', 'No fixed expenses yet', 'Ainda não há despesas fixas'),
('calculator.settings.noConsumables', 'calculator', 'settings', 'text', 'No consumables yet', 'Ainda não há consumíveis'),
('calculator.settings.noShipping', 'calculator', 'settings', 'text', 'No shipping options yet', 'Ainda não há opções de envio'),
('calculator.settings.hourlyRate', 'calculator', 'settings', 'text', 'Hourly Rate (€)', 'Taxa Horária (€)'),
('calculator.settings.hourlyRateHint', 'calculator', 'settings', 'text', 'Your hourly labor rate for time spent on prints', 'A sua taxa horária de mão de obra para o tempo gasto em impressões'),
('calculator.settings.saveLaborSettings', 'calculator', 'settings', 'text', 'Save Labor Settings', 'Guardar Configurações de Mão de Obra'),

-- SetupWizard
('calculator.setup.welcomeTitle', 'calculator', 'setup', 'text', 'Welcome to Price Calculator', 'Bem-vindo à Calculadora de Preços'),
('calculator.setup.welcomeDescription', 'calculator', 'setup', 'text', 'Let''s set up your calculator in just a few steps. We''ll add your first printer, filament, and electricity settings.', 'Vamos configurar a sua calculadora em apenas alguns passos. Iremos adicionar a sua primeira impressora, filamento e configurações de eletricidade.'),
('calculator.setup.addYourPrinter', 'calculator', 'setup', 'text', 'Add Your Printer', 'Adicionar a Sua Impressora'),
('calculator.setup.printerDescription', 'calculator', 'setup', 'text', 'Configure your 3D printer with power and depreciation settings', 'Configure a sua impressora 3D com definições de potência e depreciação'),
('calculator.setup.addYourFilament', 'calculator', 'setup', 'text', 'Add Your Filament', 'Adicionar o Seu Filamento'),
('calculator.setup.filamentDescription', 'calculator', 'setup', 'text', 'Set up filament costs per gram for accurate calculations', 'Configure os custos de filamento por grama para cálculos precisos'),
('calculator.setup.electricityCosts', 'calculator', 'setup', 'text', 'Electricity Costs', 'Custos de Eletricidade'),
('calculator.setup.electricityDescription', 'calculator', 'setup', 'text', 'Configure your electricity rate for energy cost calculations', 'Configure a sua tarifa de eletricidade para cálculos de custos de energia'),
('calculator.setup.getStarted', 'calculator', 'setup', 'text', 'Get Started', 'Começar'),
('calculator.setup.setupComplete', 'calculator', 'setup', 'text', 'Setup Complete!', 'Configuração Concluída!'),
('calculator.setup.setupCompleteDescription', 'calculator', 'setup', 'text', 'You''re all set! Your calculator is ready to use. Start by creating your first print calculation.', 'Está tudo pronto! A sua calculadora está pronta a usar. Comece criando o seu primeiro cálculo de impressão.'),
('calculator.setup.printerConfigured', 'calculator', 'setup', 'text', 'Printer configured', 'Impressora configurada'),
('calculator.setup.filamentAdded', 'calculator', 'setup', 'text', 'Filament added', 'Filamento adicionado'),
('calculator.setup.electricitySaved', 'calculator', 'setup', 'text', 'Electricity settings saved', 'Configurações de eletricidade guardadas'),
('calculator.setup.startCalculating', 'calculator', 'setup', 'text', 'Start Calculating', 'Começar a Calcular'),
('calculator.setup.back', 'calculator', 'setup', 'text', 'Back', 'Voltar'),
('calculator.setup.continue', 'calculator', 'setup', 'text', 'Continue', 'Continuar'),
('calculator.setup.saveAndContinue', 'calculator', 'setup', 'text', 'Save & Continue', 'Guardar e Continuar'),
('calculator.setup.saveAndFinish', 'calculator', 'setup', 'text', 'Save & Finish', 'Guardar e Terminar'),

-- Setup Steps
('calculator.setup.printerStep.title', 'calculator', 'setup', 'text', 'Add Your First Printer', 'Adicionar a Sua Primeira Impressora'),
('calculator.setup.printerStep.description', 'calculator', 'setup', 'text', 'Configure your 3D printer. We''ll use this to calculate depreciation and power costs.', 'Configure a sua impressora 3D. Usaremos isto para calcular depreciação e custos de energia.'),
('calculator.setup.printerStep.alreadyAdded', 'calculator', 'setup', 'text', 'Printer Already Added', 'Impressora Já Adicionada'),
('calculator.setup.printerStep.alreadyAddedDescription', 'calculator', 'setup', 'text', 'You already have a printer configured. Continue to the next step.', 'Já tem uma impressora configurada. Continue para o próximo passo.'),
('calculator.setup.printerStep.depreciationHint', 'calculator', 'setup', 'text', 'How long before the printer is fully depreciated', 'Quanto tempo até a impressora estar totalmente depreciada'),

('calculator.setup.filamentStep.title', 'calculator', 'setup', 'text', 'Add Your First Filament', 'Adicionar o Seu Primeiro Filamento'),
('calculator.setup.filamentStep.description', 'calculator', 'setup', 'text', 'Set up your filament inventory. We''ll calculate cost per gram automatically.', 'Configure o seu inventário de filamentos. Calcularemos o custo por grama automaticamente.'),
('calculator.setup.filamentStep.alreadyAdded', 'calculator', 'setup', 'text', 'Filament Already Added', 'Filamento Já Adicionado'),
('calculator.setup.filamentStep.alreadyAddedDescription', 'calculator', 'setup', 'text', 'You already have filament configured. Continue to the next step.', 'Já tem filamento configurado. Continue para o próximo passo.'),
('calculator.setup.filamentStep.costPerGram', 'calculator', 'setup', 'text', 'Cost per gram', 'Custo por grama'),

('calculator.setup.electricityStep.title', 'calculator', 'setup', 'text', 'Configure Electricity Costs', 'Configurar Custos de Eletricidade'),
('calculator.setup.electricityStep.description', 'calculator', 'setup', 'text', 'Set your electricity rate to accurately calculate power costs for printing.', 'Defina a sua tarifa de eletricidade para calcular com precisão os custos de energia para impressão.'),
('calculator.setup.electricityStep.alreadyConfigured', 'calculator', 'setup', 'text', 'Electricity Already Configured', 'Eletricidade Já Configurada'),
('calculator.setup.electricityStep.alreadyConfiguredDescription', 'calculator', 'setup', 'text', 'You already have electricity settings. Continue to finish setup.', 'Já tem configurações de eletricidade. Continue para terminar a configuração.'),
('calculator.setup.electricityStep.configName', 'calculator', 'setup', 'text', 'Configuration Name', 'Nome da Configuração'),
('calculator.setup.electricityStep.pricePerKwh', 'calculator', 'setup', 'text', 'Price per kWh (€)', 'Preço por kWh (€)'),
('calculator.setup.electricityStep.priceHint', 'calculator', 'setup', 'text', 'Check your electricity bill for the exact rate. Average in Portugal: €0.15/kWh', 'Verifique a sua fatura de eletricidade para a tarifa exata. Média em Portugal: 0,15€/kWh'),
('calculator.setup.electricityStep.contractedPower', 'calculator', 'setup', 'text', 'Contracted Power (kVA)', 'Potência Contratada (kVA)'),
('calculator.setup.electricityStep.contractedPowerHint', 'calculator', 'setup', 'text', 'Optional: Your contracted power capacity', 'Opcional: A sua capacidade de potência contratada'),
('calculator.setup.electricityStep.exampleTitle', 'calculator', 'setup', 'text', 'Example: 10-hour print at 200W', 'Exemplo: Impressão de 10 horas a 200W'),
('calculator.setup.electricityStep.electricityCost', 'calculator', 'setup', 'text', 'electricity cost', 'custo de eletricidade'),

-- MultiFilamentSelector
('calculator.multiFilament.title', 'calculator', 'multiFilament', 'text', 'Filaments Used', 'Filamentos Utilizados'),
('calculator.multiFilament.addFilament', 'calculator', 'multiFilament', 'text', 'Add Filament', 'Adicionar Filamento'),
('calculator.multiFilament.noFilaments', 'calculator', 'multiFilament', 'text', 'No filaments selected. Click "Add Filament" to begin.', 'Nenhum filamento selecionado. Clique em "Adicionar Filamento" para começar.'),
('calculator.multiFilament.filament', 'calculator', 'multiFilament', 'text', 'Filament', 'Filamento'),
('calculator.multiFilament.grams', 'calculator', 'multiFilament', 'text', 'Grams', 'Gramas'),
('calculator.multiFilament.cost', 'calculator', 'multiFilament', 'text', 'Cost', 'Custo'),
('calculator.multiFilament.selectFilament', 'calculator', 'multiFilament', 'text', 'Select filament', 'Selecionar filamento'),
('calculator.multiFilament.totalCost', 'calculator', 'multiFilament', 'text', 'Total Filament Cost', 'Custo Total de Filamento'),

-- Common
('calculator.common.error', 'calculator', 'common', 'text', 'Error', 'Erro'),
('calculator.common.loading', 'calculator', 'common', 'text', 'Loading...', 'A carregar...'),
('calculator.common.saving', 'calculator', 'common', 'text', 'Saving...', 'A guardar...'),
('calculator.common.saved', 'calculator', 'common', 'text', 'Saved', 'Guardado'),
('calculator.common.deleted', 'calculator', 'common', 'text', 'Deleted', 'Eliminado'),
('calculator.common.updated', 'calculator', 'common', 'text', 'Updated', 'Atualizado'),
('calculator.common.confirmDelete', 'calculator', 'common', 'text', 'Are you sure you want to delete this?', 'Tem a certeza de que pretende eliminar isto?'),
('calculator.common.unsavedChangesWarning', 'calculator', 'common', 'text', 'You have unsaved changes. Are you sure you want to leave?', 'Tem alterações não guardadas. Tem a certeza de que pretende sair?'),
('calculator.common.optionalNotes', 'calculator', 'common', 'text', 'Optional notes...', 'Notas opcionais...')
ON CONFLICT (content_key) DO UPDATE SET
  english_text = EXCLUDED.english_text,
  portuguese_text = EXCLUDED.portuguese_text,
  page = EXCLUDED.page,
  section = EXCLUDED.section,
  updated_at = now();